[package]
name = "kakusu"
version = "0.1.0"
authors = ["Renell Castro <renellc9819@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
clap = "2.33.1"
